### ISSUE TITLE
ERROR: No basis found for brep

### ISSUE THREAD

**Issue by Raukie** [xeokit/xeokit-convert#94] opened 2022-12-21 14:52 UTC
My conversion recieves 5 of those errors and then stops doing anything. 
But it doesnt exit the command yet no progress is made.
Is there a fix for this.

It is an ifc2xkt conversion using the IFC2X3 schema

**Comment by Trigger93** [comment] 2023-06-15 09:51
I have the same problem here.

**Comment by xeolabs** [comment] 2023-06-15 11:05
Closing this ticket because there's no information on how to reproduce the issue. 
If the issue persists, then we can reopen if someone can provide proper info to debug it, such as CLI output and maybe the IFC file itself.

**Closed as completed by xeolabs** 2023-06-15 11:05 UTC
Labels: invalid
